- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
> variable_type in Variable model is optional now

- pom.xml
- ppddm-agent/src/main/resources/application.conf
- ppddm-agent/src/main/resources/log4j.xml
- ppddm-agent/src/main/scala/ppddm/agent/Agent.scala
- ppddm-agent/src/main/scala/ppddm/agent/config/AgentConfig.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/QueryHandler.scala
- ppddm-agent/src/main/scala/ppddm/agent/gateway/api/directive/AgentExceptionHandler.scala
- ppddm-core/src/main/scala/ppddm/core/fhir/r4/service/FHIRClient.scala
- FHIR repository communication for query processing is restructured and optimized
- onfhir-path is added to the libraries for FHIRPath evaluation
> Ppddm agent eligibility query

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/QueryHandler.scala
- ppddm-core/src/main/scala/ppddm/core/fhir/FHIRQuery.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestEnum.scala
- Eligibility queries can be executed with FHIRPath expressions
- Dataset can be extracted according to Featureset definitions.
Fixes #3 #10 #16 #17
> Dataset extraction

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataStoreManager.scala
- New path for datasets and statistics: `ppddm-store/:agentID/datasets/:dataset_id`, `ppddm-store/:agentID/statistics/:dataset_id` 
Fixes #34
> :bug: fix: Place agentID on ppddm store path. fixes: #34

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataStoreManager.scala
- ppddm-agent/src/main/scala/ppddm/agent/gateway/api/directive/AgentExceptionHandler.scala
- ppddm-agent/src/main/scala/ppddm/agent/gateway/api/endpoint/DataPreparationEndpoint.scala
- ppddm-manager/src/main/scala/ppddm/manager/gateway/api/endpoint/DatasetEndpoint.scala
- Fix the HTTP Responses of the REST API
- Fix the async execution of POST to /prepare endpoint of Agent
> Rest responses fix

- ppddm-manager/src/main/scala/ppddm/manager/controller/project/ProjectController.scala
> Use the correct project object while logging. fixes #68

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- Handling multiple Patient queries in the eligibilityCriteria
- Handling FHIRPath evaluation errors & invalid FHIRPath expressions
> Fix data preparation

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-core/src/main/scala/ppddm/core/fhir/FHIRQuery.scala
- Return all resources queried, not just those on the first page.
Closes #60
> :sparkles: feat(fhir-query): Return all queried resources. Closes: #60

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/StatisticsController.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-manager/src/main/resources/agents.json
- ppddm-manager/src/main/scala/ppddm/manager/Manager.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dataset/DatasetController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/query/FederatedQueryManager.scala
- ppddm-manager/src/main/scala/ppddm/manager/registry/AgentRegistry.scala
- Update the model class names to reflect the Agent entity better
> :recycle: refactor(rest-model): Update the Rest Model

- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningModelController.scala
- Only check the Agents of WeakModels within a BoostedModel for integrity check
> :bug: fix(ppddm-manager): Fix integrity check within a DataMiningModel

- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningOrchestrator.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DistributedDataMiningManager.scala
- Testing was calling the validation URI mistakenly, it is fixed.
> :bug: fix(ppddm-manager): Use the correct URI for model testing.

- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dataset/DatasetController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningModelController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningOrchestrator.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/featureset/FeaturesetController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/project/ProjectController.scala
- Improved search in memory
- Improved debug logs
> Bugfix validation

- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/DataMiningController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/DecisionTreePPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/LogisticRegressionPPDDM.scala
- ppddm-core/src/main/scala/ppddm/core/ai/Aggregator.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-manager/src/main/resources/agents.json
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningModelController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningOrchestrator.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DistributedDataMiningManager.scala
- Fix manager not getting validation results from agents issue.
> Bugfix orchestration

- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/DataMiningAlgorithm.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/DecisionTreePPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/GradientBoostedTreePPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/LogisticRegressionPPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/NaiveBayesPPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/RandomForestPPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/SupportVectorMachinePPDDM.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestEnum.scala
- Implement Random Forest Classification
- Implement Gradient Boosted Tree Classification
- Implement Support Vector Classification
- Implement Naive Bayes Classification
- Introduce base train method and simplify algorithm specific super classes
All classification algorithms for PPDDM is now implemented.
> Classification algorithms

- ppddm-manager/pom.xml
- ppddm-manager/src/main/scala/ppddm/manager/gateway/api/endpoint/ProspectiveStudyEndpoint.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/ProspectiveStudyEndpointTest.scala
- Fix HTTP 404 Not found error in /prospective/predict endpoint
- Fix ERROR org.apache.spark.ml.util.Instrumentation: java.lang.ClassNotFoundException: Failed to find data source: parquet. Please find packages at http://spark.apache.org/third-party-projects.html
> Bug fix prediction

- ppddm-core/pom.xml
- ppddm-core/src/main/scala/ppddm/core/auth/AuthContext.scala
- ppddm-core/src/main/scala/ppddm/core/auth/AuthManager.scala
- ppddm-core/src/main/scala/ppddm/core/auth/AuthModel.scala
- ppddm-core/src/main/scala/ppddm/core/db/MongoDB.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-core/src/main/scala/ppddm/core/util/JsonFormatter.scala
- ppddm-manager/src/main/resources/application.conf
- ppddm-manager/src/main/scala/ppddm/manager/Manager.scala
- ppddm-manager/src/main/scala/ppddm/manager/client/AgentClient.scala
- ppddm-manager/src/main/scala/ppddm/manager/config/ManagerConfig.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/auth/AuthenticationController.scala
- ppddm-manager/src/test/scala/ppddm/manager/PPDDMManagerEndpointTest.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/DataMiningModelEndpointTest.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/DatasetEndpointTest.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/FeaturesetEndpointTest.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/ProjectEndpointTest.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/ProspectiveStudyEndpointTest.scala
…uth server has been implemented. closes #62
- ppddm-manager authenticates itself with the auth server.
- ppddm-manager interacts with the auth server for introspection.
- ppddm-manager maintains a cache for introspection.
Fixes #62
> Auth integration for the ppddm-manager

- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/ARLController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/ClassificationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/DataAnalysisManager.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/DataMiningController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/arl/ARLAlgorithm.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/classification/ClassificationAlgorithm.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/exception/DataMiningException.scala
- ppddm-agent/src/main/scala/ppddm/agent/exception/DataPreparationException.scala
- ppddm-agent/src/main/scala/ppddm/agent/gateway/api/directive/AgentExceptionHandler.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/ExceptionModel.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/algorithm/AlgorithmController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningModelController.scala
- Error handling mechanism in Agent
- User friendly names for algorithms
- Handling of null selection_status
> Minor improvements

- ppddm-agent/src/test/resources/data-preparation-requests/data-preparation-request-with-error.json
- ppddm-agent/src/test/scala/ppddm/agent/api/endpoint/DataPreparationEndpointTest.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestEnum.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dataset/FederatedQueryManager.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/PredictionMiningProcessor.scala
- ppddm-manager/src/test/scala/ppddm/manager/api/endpoint/AlgorithmEndpointTest.scala
- Errors are now handled on ppddm-agent and ppddm-manager so that the platform can be informed if an error occurs during PPDDM operations.
> Error handling

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/QueryHandler.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestEnum.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- An encounter-based data preparation approach has been implemented
> New preparation

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/algorithm/AlgorithmController.scala
- Remove Naive Bayes from the list of available algorithms
-
-
> :recycle: refactor(AlgorithmController): Remove Naive Bayes from the list of available algorithms.

- docker/ppddm-manager/docker-entrypoint.sh
- ppddm-core/src/main/scala/ppddm/core/ai/Aggregator.scala
- ppddm-manager/src/main/resources/application.conf
- ppddm-manager/src/main/scala/ppddm/manager/config/ManagerConfig.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningModelController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningOrchestrator.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DistributedDataMiningManager.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/PredictionMiningProcessor.scala
- Bug fixes and improvements
Fixes #182
> Bug fixing

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestModel.scala
- Enhancement of encounter based variable calculations.
- Encounter.type is being checked while calculating readmission value. (Encounter.type = 'unplanned')
- New eligibilityCriterion parameter (value:readmission:30) was set for the exclusion criteria: 'Programmed admission in any hospital department with the 30 days after the hospitalization'.
> Data preparation

- pom.xml
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/ARLController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/ClassificationController.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/DataAnalysisManager.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/arl/FPGrowthPPDDM.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/dm/algorithm/classification/ClassificationAlgorithm.scala
- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-core/src/main/scala/ppddm/core/ai/PipelineModelEncoderDecoder.scala
- ppddm-core/src/main/scala/ppddm/core/store/DataStoreManager.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/auth/AuthenticationController.scala
- ppddm-manager/src/main/scala/ppddm/manager/controller/dm/DataMiningOrchestrator.scala
- Model creation is fixed for prediction projects.
> :bug: fix(ppddm): Model creation issues have been fixed.

- ppddm-agent/src/main/scala/ppddm/agent/controller/prepare/DataPreparationController.scala
- ppddm-core/src/main/scala/ppddm/core/fhir/FHIRClient.scala
- ppddm-core/src/main/scala/ppddm/core/rest/model/RestEnum.scala
- Correct implementation of the mortality at 6 months by using a specific FHIRPath function in the form of "value:mortality:6".
- The last part (6 months) is parametric, the user can specify the number of months to look back.
> Mortality at month
